### ISSUE TITLE
Request: removeAll without change trigger

### ISSUE THREAD

**Issue by sirdemoncze** [moreonion/jquery.formprefill#4]
Hello, 

first of all, thank you for your work on this plugin :-).

Would it be possible to edit function **removeAll** without trigger **change**? 

I used triggers **change** and **keyup** (on inputs) for ajax filtering. In my case, calling function **removeAll**, creating many ajax requests (one per input). 

It would be nice to use own trigger after clear form ;-).

For example:
```
if (options.resetFields || options.resetFieldsWithoutTrigger) {
    $inputs.each(function() {
        var $field = $(this), api = $field.data('formPrefill');

        var type = $field.attr('type');

        if (type == 'radio' || type == 'checkbox') {
            $field[0].checked = api.initialValue;
        } 
        else {
            $field.val(api.initialValue);
        }
        
        if (!options.resetFieldsWithoutTrigger)
            $field.trigger('change');    
    });
}
```

**Comment by torotil** [comment]
I’d prefer to avoid the complexity of adding a new configuration option.

Would

```javascript
$inputs.each(function() {
  var $field = $(this), api = $field.data('formPrefill');
  var type = $field.attr('type');

  if (type == 'radio' || type == 'checkbox') {
      $field[0].checked = api.initialValue;
  } 
  else {
      $field.val(api.initialValue);
  }
  // No $field.trigger() inside the each!
}).trigger('change');
```
solve the issue for you?

**Comment by sirdemoncze** [comment]
Hi, i prefer better solution then new option too, but your edit is same **as before** :-(.
Per each item in $inputs call trigger **change**.

**Comment by torotil** [comment]
> Hi, i prefer better solution then new option too, but your edit is same **as before** :-(.
> Per each item in $inputs call trigger **change**.

Have you tried it? It invokes `trigger()` only once.

**Comment by torotil** [comment]
Ok I see. This still invokes the change multiple times. But then again, all the inputs did change so sending a change event for it is correct.

From your posting I’d guess you are trying to do a ajax-autosubmit for a form. I’d suggest to add a functionality for this that collects multiple change events within a short time. This is a standard feature of such auto-submits.

**Comment by sirdemoncze** [comment]
Exactly, as you say. 

OK, its good idea with collects multiple changes ;-) (some timeout after 1st change). 

Thank's for you time.
